import argparse
import json
import re
import time
from pathlib import Path

from sqlglot import parse_one, exp

from dataset_loader import load_dataset_config
from query_loader import load_all_sql_queries
from sql_parser import parse_sql
from planner import build_plan
from yaml_builder import build_yaml
from runner import run_docetl
from exporter import json_to_csv, json_to_query_csv
from evaluate_all import run_evaluation
from utils import repo_root, dataset_real_name


def _required_sql_columns(sql: str) -> set[str]:
    try:
        tree = parse_one(sql, error_level="ignore")
    except Exception:
        tree = None
    if tree is None:
        return set()

    cols: set[str] = set()
    for col in tree.find_all(exp.Column):
        if col.name:
            cols.add(col.name)
    return cols


def _is_transient_docetl_content_filter_error(exc: Exception) -> bool:
    msg = str(exc)
    patterns = [
        "InvalidOutputError: No tool calls in LLM response",
        "finish_reason='content_filter'",
        "Tool calls generated by LLM: []",
    ]
    return any(p in msg for p in patterns)


def _run_docetl_with_retries(yaml_path: Path, max_attempts: int = 3) -> None:
    last_exc: Exception | None = None
    for attempt in range(1, max_attempts + 1):
        try:
            run_docetl(str(yaml_path))
            return
        except Exception as exc:
            last_exc = exc
            if not _is_transient_docetl_content_filter_error(exc):
                raise
            if attempt >= max_attempts:
                raise
            wait_s = 2 * attempt
            print(
                f"  WARN -> DocETL content-filter transient (tentativo {attempt}/{max_attempts}), "
                f"retry tra {wait_s}s"
            )
            time.sleep(wait_s)
    if last_exc is not None:
        raise last_exc


def _json_columns(json_path: Path) -> set[str]:
    if not json_path.exists():
        return set()
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return set()

    if isinstance(data, dict):
        data = [data]
    if not isinstance(data, list):
        return set()

    cols: set[str] = set()
    for row in data[:50]:
        if isinstance(row, dict):
            cols.update(row.keys())
    return cols


def _load_json_rows(json_path: Path) -> list[dict]:
    if not json_path.exists():
        return []
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return []
    if isinstance(data, dict):
        data = [data]
    if not isinstance(data, list):
        return []
    return [r for r in data if isinstance(r, dict)]


def _build_field_type_map(config: dict) -> dict[str, str]:
    out: dict[str, str] = {}
    for _, table_cfg in config.get("tables", {}).items():
        for field, dtype in table_cfg.get("fields", {}).items():
            out.setdefault(str(field), str(dtype))
    return out


def _is_numeric_dtype(dtype: str) -> bool:
    return str(dtype).lower() in {"int", "float", "number", "numeric"}


def _is_parseable_number(value) -> bool:
    if value is None:
        return False
    s = str(value).strip()
    if not s:
        return False
    s = re.sub(r"^\((.*)\)$", r"-\1", s)
    s = re.sub(r"[$â‚¬Â£Â¥â‚¹,%]", "", s)
    s = s.replace(",", "")
    s = re.sub(r"[^0-9eE+\-.]", "", s)
    if not s:
        return False
    try:
        float(s)
        return True
    except Exception:
        return False


def _low_quality_fields(rows: list[dict], required_fields: set[str], field_types: dict[str, str]) -> set[str]:
    if not rows or not required_fields:
        return set(required_fields) if required_fields else set()

    bad: set[str] = set()
    n = len(rows)

    for field in sorted(required_fields):
        dtype = field_types.get(field, "string")
        invalid = 0
        present_once = False
        for row in rows:
            if field not in row:
                invalid += 1
                continue
            value = row.get(field)
            if value is None or (isinstance(value, str) and not value.strip()):
                invalid += 1
                continue
            present_once = True
            if _is_numeric_dtype(dtype) and not _is_parseable_number(value):
                invalid += 1

        if not present_once:
            bad.add(field)
            continue

        invalid_ratio = invalid / n if n else 1.0
        threshold = 0.50 if _is_numeric_dtype(dtype) else 0.85
        if invalid_ratio > threshold:
            bad.add(field)

    return bad


def _augment_plan_with_missing_fields(plan: dict, config: dict, missing: set[str]) -> bool:
    if not missing:
        return False
    changed = False
    table_cfgs = config.get("tables", {})
    extract_fields = plan.setdefault("extract_fields", {})

    for field in sorted(missing):
        clean = field.split(".")[-1]
        found_table = None
        for table_name, cfg in table_cfgs.items():
            if clean in cfg.get("fields", {}):
                found_table = table_name
                break
        if not found_table:
            continue
        extract_fields.setdefault(found_table, [])
        if clean not in extract_fields[found_table]:
            extract_fields[found_table].append(clean)
            changed = True
    return changed


def run_dataset(dataset_name: str, rebuild: bool = False):
    root = repo_root()

    config = load_dataset_config(dataset_name)
    queries = load_all_sql_queries(dataset_name)
    attributes_path = root / "Query" / dataset_name / f"{dataset_name}_attributes.json"
    try:
        attributes = json.loads(attributes_path.read_text(encoding="utf-8"))
    except Exception:
        attributes = None
    field_types = _build_field_type_map(config)

    out_root = root / "systems" / "DocETL" / "outputs" / dataset_real_name(dataset_name)
    yaml_root = out_root / "yaml"
    json_root = out_root / "json"
    csv_root = out_root / "csv"

    yaml_root.mkdir(parents=True, exist_ok=True)
    json_root.mkdir(parents=True, exist_ok=True)
    csv_root.mkdir(parents=True, exist_ok=True)

    total = len(queries)
    ok = 0
    failed = 0
    skipped = 0

    for idx, query_meta in enumerate(queries, start=1):
        print(f"[{idx}/{total}] {query_meta['id']}")

        try:
            query_id = query_meta["id"]
            json_path = json_root / f"{query_id}.json"
            csv_path = csv_root / f"{query_id}.csv"

            # Resume mode: if both outputs already exist, skip expensive rerun.
            if not rebuild and json_path.exists() and csv_path.exists():
                skipped += 1
                print(f"  SKIP -> {csv_path.name} (giÃ  presente)")
                continue

            parsed = parse_sql(query_meta["sql"])
            plan = build_plan(config, parsed, query_meta)

            yaml_path_str, json_path_str = build_yaml(
                config=config,
                plan=plan,
                yaml_output_dir=str(yaml_root),
                json_output_dir=str(json_root),
                strict_mode=False,
            )
            yaml_path = Path(yaml_path_str)
            json_path = Path(json_path_str)

            _run_docetl_with_retries(yaml_path)

            # Retry once with targeted missing fields required by SQL.
            required_cols = _required_sql_columns(query_meta["sql"])
            produced_cols = _json_columns(json_path)
            missing_cols = required_cols - produced_cols
            did_retry = False
            if missing_cols and _augment_plan_with_missing_fields(plan, config, missing_cols):
                print(f"  INFO -> retry estrazione campi mancanti: {sorted(missing_cols)}")
                yaml_path_str, json_path_str = build_yaml(
                    config=config,
                    plan=plan,
                    yaml_output_dir=str(yaml_root),
                    json_output_dir=str(json_root),
                    strict_mode=True,
                )
                yaml_path = Path(yaml_path_str)
                json_path = Path(json_path_str)
                _run_docetl_with_retries(yaml_path)
                did_retry = True

            # Retry once in strict mode if required fields are mostly missing/invalid.
            rows = _load_json_rows(json_path)
            low_quality = _low_quality_fields(rows, required_cols, field_types)
            if low_quality and not did_retry:
                _augment_plan_with_missing_fields(plan, config, low_quality)
                print(f"  INFO -> retry qualitÃ  bassa campi: {sorted(low_quality)}")
                yaml_path_str, json_path_str = build_yaml(
                    config=config,
                    plan=plan,
                    yaml_output_dir=str(yaml_root),
                    json_output_dir=str(json_root),
                    strict_mode=True,
                )
                yaml_path = Path(yaml_path_str)
                json_path = Path(json_path_str)
                _run_docetl_with_retries(yaml_path)

            try:
                json_to_query_csv(
                    json_path=str(json_path),
                    csv_path=str(csv_path),
                    query_sql=query_meta["sql"],
                    config=config,
                    attributes=attributes,
                )
            except Exception as export_err:
                # Fallback to raw export so a single post-processing failure
                # doesn't stop the full dataset run.
                print(f"  WARN -> post-processing SQL fallito, uso export raw ({export_err})")
                json_to_csv(str(json_path), str(csv_path))

            ok += 1
            print(f"  OK -> {csv_path.name}")

        except Exception as e:
            failed += 1
            print(f"  ERROR -> {e}")

    print("\n=== RIEPILOGO ===")
    print(f"Dataset: {dataset_name}")
    print(f"Totali : {total}")
    print(f"OK     : {ok}")
    print(f"Skip   : {skipped}")
    print(f"Errori : {failed}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", required=True, help="Nome cartella dataset, es. Finan, Player, Legal")
    parser.add_argument(
        "--rebuild",
        action="store_true",
        help="Riesegue tutte le query ignorando i risultati gia presenti",
    )
    parser.add_argument(
        "--eval",
        action="store_true",
        help="Esegue anche la evaluation batch al termine della pipeline",
    )
    parser.add_argument(
        "--eval-only",
        action="store_true",
        help="Salta la pipeline e lancia solo evaluation",
    )
    parser.add_argument(
        "--rebuild-eval",
        action="store_true",
        help="Riesegue evaluation anche se acc.json gia presente",
    )
    parser.add_argument(
        "--query-type",
        default="all",
        choices=["all", "agg", "filter", "select", "mixed", "join"],
        help="Categoria query da valutare (all, agg, filter, select, mixed, join)",
    )
    args = parser.parse_args()

    if not args.eval_only:
        run_dataset(args.dataset, rebuild=args.rebuild)
    if args.eval or args.eval_only:
        run_evaluation(args.dataset, rebuild=args.rebuild_eval, query_type=args.query_type)
